### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by numelion** [bilginnet/yii2-cropper#7]
You don't write a form and controller example in readme.
In which action submit request goes to? How to set it right? How must be written controller action code to receive request and save "data:image" content to $model->_photo variable?
Why request with "data:image" is GET? Why not POST?

> Request Method: GET
> Status Code: 200 OK (from memory cache)
> Referrer Policy: no-referrer-when-downgrade

**Comment by bilginnet** [comment]
-Didn't read my "readme file" ?
-Find that title "Simple usage in _form file" in readme file.
-No need write any code in controller/action. because this image creating into model file in "beforeSave" -event.
-Check your form method for request. This widget work on GET - POST request both.
-Also you can create your own behavior class for model file beforeSave event.


Let's add  in your model file
Customize your virtual $attribute in this model file and use this attribute. Sample: public $_photo;
Image will be create in beforeSave event
````php
    public $_image

    public function rules()
    {
        return [
            ['_image', 'safe'],
        ];
    }
    
    public function beforeSave($insert)
    {
        if (is_string($this->_image) && strstr($this->_image, 'data:image')) {

            // creating image file as png
            $data = $this->_image;
            $data = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $data));
            $fileName = time() . '-' . rand(100000, 999999) . '.png';
            file_put_contents(Yii::getAlias('@uploadPath') . '/' . $fileName, $data);


            // deleting old image 
            // $this->image is real attribute for filename in table
            // customize your code for your attribute            
            if (!$this->isNewRecord && !empty($this->image)) {
                unlink(Yii::getAlias('@uploadPath/'.$this->image));
            }
            
            // set new filename
            $this->image = $fileName;
        }

        return parent::beforeSave($insert);
    }
````
